
server:
  port: 56012
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          #uri: lb://server2 #匹配后提供服务的路由地址
          uri: http://localhost:56010 #匹配后提供服务的路由地址
          predicates:
            - Path=/customerUser/** #断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
